// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function CheckLeannStatus():Promise<main.LeannStatus>;

export function ClearChatHistory():Promise<void>;

export function CreateNote(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Note>;

export function DeleteChatMessage(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function GetAllNotes():Promise<Array<main.Note>>;

export function GetAllSettings():Promise<Record<string, string>>;

export function GetAppDir():Promise<string>;

export function GetChatHistory():Promise<Array<main.ChatMessage>>;

export function GetNoteCategories():Promise<Array<string>>;

export function GetSetting(arg1:string):Promise<string>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function RebuildIndex():Promise<void>;

export function RebuildIndexIfChanged():Promise<boolean>;

export function SendChatMessage(arg1:string):Promise<main.ChatResponse>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function TestLLMConnection():Promise<main.TestConnectionResult>;

export function UpdateNote(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Note>;
