// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLeannStatus() {
  return window['go']['main']['App']['CheckLeannStatus']();
}

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function CreateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3, arg4);
}

export function DeleteChatMessage(arg1) {
  return window['go']['main']['App']['DeleteChatMessage'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetAppDir() {
  return window['go']['main']['App']['GetAppDir']();
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetNoteCategories() {
  return window['go']['main']['App']['GetNoteCategories']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function ImportFolder(arg1) {
  return window['go']['main']['App']['ImportFolder'](arg1);
}

export function OnBeforeClose(arg1) {
  return window['go']['main']['App']['OnBeforeClose'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['main']['App']['OnStartup'](arg1);
}

export function RebuildIndex() {
  return window['go']['main']['App']['RebuildIndex']();
}

export function RebuildIndexIfChanged() {
  return window['go']['main']['App']['RebuildIndexIfChanged']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendChatMessage(arg1) {
  return window['go']['main']['App']['SendChatMessage'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function TestLLMConnection() {
  return window['go']['main']['App']['TestLLMConnection']();
}

export function UpdateNote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3, arg4, arg5);
}
